using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CruiseDAL.DataObjects;
using CruiseDAL.Schema;


namespace CruiseProcessing
{
    public class volumeLists
    {
        //  Region 1 equations
        public string[,] volumeArray01 = new string[14,4] {{"ALL","Balsam fir/Whitebark pine","I00FW2W012","Flewelling Profile Model"},
                                                           {"ALL","Cottonwood",               "102DVEW740","Kemp Equation"},
                                                           {"ALL","Douglas fir",              "I00FW2W202","Flewelling Profile Model"},
                                                           {"ALL","Engelmann's spruce",       "I00FW2W093","Flewelling Profile Model"},
                                                           {"ALL","Grand fir",                "I00FW2W017","Flewelling Profile Model"},
                                                           {"ALL","Larch/Limber pine",        "I00FW2W073","Flewelling Profile Model"},
                                                           {"ALL","Lodgepole pine",           "I00FW2W108","Flewelling Profile Model"},
                                                           {"ALL","Western/Mountain hemlock", "I00FW2W260","Flewelling Profile Model"},
                                                           {"ALL","Ponderosa pine",           "I00FW2W122","Flewelling Profile Model"},
                                                           {"ALL","Quaking aspen",            "102DVEW746","Kemp Equation"},
                                                           {"ALL","Subalpine fir",            "I00FW2W019","Flewelling Profile Model"},
                                                           {"ALL","Western redcedar",         "I00FW2W242","Flewelling Profile Model"},
                                                           {"ALL","Western white pine",       "I00FW2W119","Flewelling Profile Model"},
                                                           {"8",  "Ponderosa pine",           "203FW2W122","Flewelling Profile Model"}};
        //  Region 2 equations
        public string[,] volumeArray02 = new string[19,4] {{"ALL","Bur oak",               "200DVEW823","Chojnacky Equation"},
                                                           {"ALL","Douglas fir",           "200FW2W202","Flewelling Profile Model"},
                                                           {"ALL","Engelmann's spruce",    "407FW2W093","Flewelling Profile Model"},
                                                           {"ALL","Gambel oak",            "200DVEW814","Chojnacky Equation"},
                                                           {"ALL","Lodgepole pine",        "200FW2W108","Flewelling Profile Model"},
                                                           {"ALL","Mountain mahogany",     "200DVEW475","Chojnacky Equation"},
                                                           {"ALL","Oneseed juniper",       "200DVEW069","Chojnacky Equation"},
                                                           {"ALL","Other hardwoods",       "200DVEW998","Chojnacky Equation"},
                                                           {"ALL","Pinyon pine",           "200DVEW106","Chojnacky Equation"},
                                                           {"ALL","Ponderosa pine",        "200FW2W122","Flewelling Profile Model"},
                                                           {"ALL","Quaking aspen",         "200FW2W746","Flewelling Profile Model"},
                                                           {"ALL","Rocky Mountain juniper","200DVEW066","Chojnacky Equation"},
                                                           {"ALL","Subalpine fir",         "I00FW2W019","Flewelling Profile Model"},
                                                           {"ALL","White fir",             "200FW2W015","Flewelling Profile Model"},
                                                           {"ALL","Utah juniper",          "200DVEW065","Chojnacky Equation"},
                                                           {"2",  "Lodgepole pine",        "202FW2W108","Flewelling Profile Model"},
                                                           {"3",  "Ponderosa pine",        "203FW2W122","Flewelling Profile Model"},
                                                           {"13", "Ponderosa pine",        "213FW2W122","Flewelling Profile Model"},
                                                           {"14", "Lodgepole pine",        "202FW2W108","Flewelling Profile Model"}};
        //  Region 3 equations
        public string[,] volumeArray03 = new string[26,4] {{"ALL","Juniper",           "300DVEW060","Chojnacky Equation"},
                                                           {"ALL","Unknown",           "300DVEW999","Chojnacky Equation"},
                                                           {"ALL","Engelmann's spruce","300DVEW093","Hann and Bare Equation"},
                                                           {"ALL","Limber pine",       "300DVEW113","Hann and Bare Equation"},
                                                           {"ALL","Quaking aspen",     "300DVEW746","Hann and Bare Equation"},
                                                           {"ALL","Pinyon pine",       "300DVEW106","Chojnacky Equation"},
                                                           {"ALL","Maple",             "300DVEW310","Chojnacky Equation"},
                                                           {"ALL","Oak",               "300DVEW800","Chojnacky Equation"},
                                                           {"ALL","Ponderosa pine",    "300DVEW122","Eager Mill Study Equation"},
                                                           {"ALL","Black maple",       "300DVEW314","Chojnacky Equation"},
                                                           {"ALL","White fir",         "301DVEW015","Hann and Bare Equation"},
                                                           {"ALL","Douglas fir",       "301DVEW202","Hann and Bare Equation"},
                                                           {"1",  "Ponderosa pine",    "300FW2W122","Flewelling Profile Model"},
                                                           {"2",  "White fir",         "302DVEW015","Hann and Bare Equation"},
                                                           {"2",  "Douglas fir",       "302DVEW202","Hann and Bare Equation"},
                                                           {"3",  "White fir",         "302DVEW015","Hann and Bare Equation"},
                                                           {"3",  "Douglas fir",       "302DVEW202","Hann and Bare Equation"},
                                                           {"4",  "Ponderosa pine",    "300FW2W122","Flewelling Profile Model"},
                                                           {"7",  "Douglas fir",       "302DVEW202","Hann and Bare Equation"},
                                                           {"7",  "White fir",         "302DVEW015","Hann and Bare Equation"},
                                                           {"7",  "Ponderosa pine",    "300FW2W122","Flewelling Profile Model"},
                                                           {"10", "White fir",         "301FW2W015","Flewelling Profile Model"},
                                                           {"10", "Douglas fir",       "301FW2W202","Flewelling Profile Model"},
                                                           {"10", "Ponderosa Pine",    "301FW2W122","Flewelling Profile Model"},
                                                           {"10", "White pine",        "301FW2W108","Flewelling Profile Model"},
                                                           {"12", "Ponderosa pine",    "300FW2W122","Flewelling Profile Model"}};
                  
        //  Region 4 equations
        public string[,] volumeArray04 = new string[54,4] {{"ALL","Douglas fir",                    "400MATW202","Rustagi Profile Model"},
                                                           {"ALL","Engelmann's/Blue spruce",        "400MATW093","Rustagi Profile Model"},
                                                           {"ALL","Grand/White fir",                "400MATW015","Rustagi Profile Model"},
                                                           {"ALL","Lodgepole/Limber/Whitebark pine","400MATW108","Rustagi Profile Model"},
                                                           {"ALL","Mountain mahogany",              "400DVEW475","Chojnacky Equation"},
                                                           {"ALL","Other hardwoods",                "400DVEW998","Chojnacky Equation"},
                                                           {"ALL","Pinyon pine",                    "400DVEW106","Chojnacky Equation"},
                                                           {"ALL","Ponderosa pine",                 "400MATW122","Rustagi Profile Model"},
                                                           {"ALL","Quaking aspen",                  "400MATW746","Rustagi Profile Model"},
                                                           {"ALL","Rocky Mountain juniper",         "400DVEW066","Chojnacky Equation"},
                                                           {"ALL","Single leaf pinyon pine",        "400DVEW133","Chojnacky Equation"},
                                                           {"ALL","Subalpine fir",                  "400MATW019","Rustagi Profile Model"},
                                                           {"ALL","Utah juniper-Great Basin",       "400DVEW065","Chojnacky Equation"},
                                                           {"ALL","Utah juniper-Colorado Plateau",  "401DVEW065","Chojnacky Equation"},
                                                           {"ALL","Western juniper",                "400DVEW064","Chojnacky Equation"},
                                                           {"1",  "Ponderosa pine",                 "401MATW122","Rustagi Profile Model"},
                                                           {"2",  "Western larch",                  "400MATW073","Rustagi Profile Model"},
                                                           {"2",  "Engelmann's/Blue spruce",        "I15FW2W093","Flewelling Profile Model"},
                                                           {"2",  "Ponderosa pine",                 "I15FW2W122","Flewelling Profile Model"},
                                                           {"2",  "Douglas fir",                    "I15FW2W202","Flewelling Profile Model"},
                                                           {"2",  "Grand/White fir",                "I15FW2W017","Flewelling Profile Model"},
                                                           {"5",  "Subalpine fir",                  "405MATW019","Rustagi Profile Model"},
                                                           {"5",  "Douglas fir",                    "405MATW202","Rustagi Profile Model"},
                                                           {"6",  "Western larch",                  "400MATW073","Rustagi Profile Model"},
                                                           {"7",  "Ponderosa pine",                 "402MATW122","Rustagi Profile Model"},
                                                           {"7",  "Engelmann's/Blue spruce",        "407FW2W093","Flewelling Profile Model"},
                                                           {"8",  "Ponderosa pine",                 "402MATW122","Rustagi Profile Model"},
                                                           {"8",  "Engelmann's/Blue spruce",        "407MATW093","Rustagi Profile Model"},
                                                           {"9",  "Incense cedar",                  "400MATW081","Rustagi Profile Model"},
                                                           {"9",  "White fir/Mountain hemlock",     "401MATW015","Rustagi Profile Model"},
                                                           {"9",  "Ponderosa pine",                 "403MATW122","Rustagi Profile Model"},
                                                           {"9",  "Lodgepole/Limber/Whitebark pine","401MATW108","Rustagi Profile Model"},
                                                           {"9",  "California red fir",             "400MATW020","Rustagi Profile Model"},
                                                           {"9",  "Sugar/Western white pine",       "400MATW117","Rustagi Profile Model"},
                                                           {"10", "Ponderosa pine",                 "402MATW122","Rustagi Profile Model"},
                                                           {"12", "Western larch",                  "400MATW073","Rustagi Profile Model"},
                                                           {"12", "Engelmann's/Blue spruce",        "I15FW2W093","Flewelling Profile Model"},
                                                           {"12", "Douglas fir",                    "I15FW2W202","Flewelling Profile Model"},
                                                           {"12", "Grand/White fir",                "I15FW2W017","Flewelling Profile Model"},
                                                           {"12", "Ponderosa pine",                 "I15FW2W122","Flewelling Profile Model"},
                                                           {"13", "Engelmann's/Blue spruce",        "I15FW2W093","Flewelling Profile Model"},
                                                           {"13", "Western larch",                  "400MATW073","Rustagi Profile Model"},
                                                           {"13", "Douglas fir",                    "I15FW2W202","Flewelling Profile Model"},
                                                           {"13", "Grand/White fir",                "I15FW2W017","Flewelling Profile Model"},
                                                           {"13", "Ponderosa Pine",                 "I15FW2W122","Flewelling Profile Model"},
                                                           {"14", "Western larch",                  "400MATW073","Rustagi Profile Model"},
                                                           {"17", "Incense cedar",                  "400MATW081","Rustagi Profile Model"},
                                                           {"17", "Lodgepole/Limber/Whitebark pine","401MATW108","Rustagi Profile Model"},
                                                           {"17", "White fir/Mountain hemlock",     "401MATW015","Rustagi Profile Model"},
                                                           {"17", "Sugar/Western white pine",       "400MATW117","Rustagi Profile Model"},
                                                           {"17", "Ponderosa pine",                 "403MATW122","Rustagi Profile Model"},
                                                           {"17", "California red fir",             "400MATW020","Rustagi Profile Model"},
                                                           {"18", "Ponderosa pine",                 "402MATW122","Rustagi Profile Model"},
                                                           {"19", "Ponderosa pine",                 "402MATW122","Rustagi Profile Model"}};

        //  Region 5 equations
        public string[,] volumeArray05 = new string[30,4] {{"ALL","Koa",                             "H00SN2W301","Sharpnack Profile Model"},
                                                           {"ALL","Ohia",                            "H00SN2W671","Sharpnack Profile Model"},
                                                           {"ALL","Eucalyptus",                      "H00SN2W510","Sharpnack Profile Model"},
                                                           {"ALL","Eucalyptus",                      "H01SN2W510","Sharpnack Profile Model"},
                                                           {"ALL","E. spruce/Mtn. hemlock/White fir","500WO2W015","Wensel and Olsen Profile Model"},
                                                           {"ALL","Western white/Sugar pine",        "500WO2W117","Wensel and Olsen Profile Model"},
                                                           {"ALL","Engelmann's oak",                 "500DVEW811","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Tanoak",                          "500DVEW631","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Lodgepole pine",                  "500WO2W108","Wensel and Olsen Profile Model"},
                                                           {"ALL","Golden chinkapin",                "500DVEW431","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Giant sequoia",                   "500DVEW212","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Blue oak",                        "500DVEW807","Pillsbury and Kirkley Equation"},
                                                           {"ALL","California black oak",            "500DVEW818","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Bigleaf maple",                   "500DVEW312","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Red alder",                       "500DVEW351","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Interior live oak",               "500DVEW839","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Redwood",                         "500WO2W211","Wensel and Olsen Profile Model"},
                                                           {"ALL","California live oak",             "500DVEW801","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Jeffrey pine",                    "500WO2W116","Wensel and Olsen Profile Model"},
                                                           {"ALL","Incense cedar",                   "500WO2W081","Wensel and Olsen Profile Model"},
                                                           {"ALL","California red fir",              "500WO2W020","Wensel and Olsen Profile Model"},
                                                           {"ALL","Ponderosa pine",                  "500WO2W122","Wensel and Olsen Profile Model"},
                                                           {"ALL","Douglas fir",                     "500WO2W202","Wensel and Olsen Profile Model"},
                                                           {"ALL","Juniper",                         "500DVEW060","Pillsbury and Kirkley Equation"},
                                                           {"ALL","California white oak",            "500DVEW821","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Oregon white oak",                "500DVEW815","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Pacific madrone",                 "500DVEW361","Pillsbury and Krikley Equation"},
                                                           {"ALL","California laurel",               "500DVEW981","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Canyon live oak",                 "500DVEW805","Pillsbury and Kirkley Equation"},
                                                           {"ALL","Grand fir",                       "I15FW2W017","Flewelling-Central Idaho Model"}};

         //  per C. Bodenhausen, April 2017, remove all equations related to 532                                                         
/*                                                         {"5",  "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"5",  "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"5",  "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"5",  "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"5",  "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"5",  "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"5",  "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"5",  "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"5",  "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"},
                                                           {"6",  "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"6",  "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"6",  "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"6",  "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"6",  "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"6",  "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"6",  "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"6",  "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"6",  "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"},
                                                           {"8",  "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"8",  "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"8",  "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"8",  "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"8",  "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"8",  "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"8",  "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"8",  "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"8",  "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"},
                                                           {"9",  "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"9",  "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"9",  "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"9",  "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"9",  "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"9",  "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"9",  "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"9",  "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"9",  "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"},
                                                           {"10", "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"10", "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"10", "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"10", "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"10", "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"10", "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"10", "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"10", "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"10", "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"},
                                                           {"14", "Ponderosa pine",                  "532WO2W122","Wensel and Olsen Profile Model"},
                                                           {"14", "Jeffrey pine",                    "532WO2W116","Wensel and Olsen Profile Model"},
                                                           {"14", "Sugar pine",                      "532WO2W117","Wensel and Olsen Profile Model"},
                                                           {"14", "White fir",                       "532WO2W015","Wensel and Olsen Profile Model"},
                                                           {"14", "California red fir",              "532WO2W020","Wensel and Olsen Profile Model"},
                                                           {"14", "Douglas fir",                     "532WO2W202","Wensel and Olsen Profile Model"},
                                                           {"14", "Incense cedar",                   "532WO2W081","Wensel and Olsen Profile Model"},
                                                           {"14", "Lodgepole pine",                  "532WO2W108","Wensel and Olsen Profile Model"},
                                                           {"14", "Redwood",                         "532WO2W211","Wensel and Olsen Profile Model"}};

 */
        //  Region 6 equations
        public string[,] volumeArray06 = new string[89,4] {{"ALL","All coniferous",                      "616BEHW000","Behr's Hyperbola"},
                                                           {"1",  "Douglas fir",                         "I11FW2W202","INGY 2 Point"},
                                                           {"1",  "White fir/Shasta fir",                "I00FW2W017","INGY 2 Point"},
                                                           {"1",  "Lodgepole pine",                      "I11FW2W108","INGY 2 Point"},
                                                           {"1",  "Ponderosa pine",                      "I11FW2W122","INGY 2 Point"},
                                                           {"1",  "Western larch",                       "I11FW2W073","INGY 2 Point"},
                                                           {"1",  "Incense cedar",                       "I11FW2W242","INGY 2 Point"},
                                                           {"1",  "Sugar pine",                          "I13FW2W122","INGY 2 Point"},
                                                           {"2",  "Incense cedar",                       "I00FW2W202","INGY 2 Point"},
                                                           {"2",  "Douglas fir",                         "I00FW2W017","INGY 2 Point"},
                                                           {"2",  "Grand fir/White fir",                 "I11FW2W017","INGY 2 Point"},
                                                           {"2",  "Lodgepole pine",                      "I00FW2W108","INGY 2 Point"},
                                                           {"2",  "Ponderosa pine",                      "I00FW2W122","INGY 2 Point"},
                                                           {"3",  "Pacific silver fir",                  "I12FW2W017","INGY 2 Point"},
                                                           {"3",  "Douglas fir",                         "F03FW2W202","Flewelling Westside"},
                                                           {"3",  "Douglas fir",                         "F07FW2W202","Flewelling Westside"},
                                                           {"3",  "Western hemlock",                     "F00FW2W263","Flewelling Westside"},
                                                           {"3",  "Western hemlock",                     "F04FW2W263","Flewelling Westside"},
                                                           {"3",  "Western hemlock",                     "F06FW2W263","Flewelling Westside"},
                                                           {"3",  "Subalpine fir",                       "I00FW2W108","INGY Area Wide"},
                                                           {"4",  "Grand fir/White fir",                 "I12FW2W017","INGY 2 Point"},
                                                           {"4",  "Lodgepole pine",                      "I12FW2W108","INGY 2 Point"},
                                                           {"4",  "Ponderosa pine",                      "I12FW2W122","INGY 2 Point"},
                                                           {"4",  "Douglas fir",                         "I12FW2W202","INGY 2 Point"},
                                                           {"5",  "Douglas fir",                         "F08FW2W202","Flewelling Westside"},
                                                           {"5",  "Western hemlock",                     "F03FW2W263","Flewelling Westside"},
                                                           {"6",  "Western hemlock",                     "I11FW2W260","INGY 2 Point"},
                                                           {"6",  "Pacific silver fir",                  "I12FW2W017","INGY 2 Point"},
                                                           {"6",  "Noble fir/Grand fir",                 "I13FW2W017","INGY 2 Point"},
                                                           {"6",  "Douglas fir",                         "F05FW2W202","Flewelling Westside"},
                                                           {"6",  "Douglas fir",                         "F03FW2W202","Flewelling Westside"},
                                                           {"6",  "Englemann spruce",                    "I11FW2W093","INGY 2 Point"},
                                                           {"6",  "Lodgepole pine",                      "I11FW2W108","INGY 2 Point"},
                                                           {"6",  "Ponderosa pine",                      "I12FW2W122","INGY 2 Point"},
                                                           {"7",  "Grand fir/White fir",                 "I12FW2W017","INGY 2 Point"},
                                                           {"7",  "Western larch",                       "I12FW2W073","INGY 2 Point"},
                                                           {"7",  "Lodgepole pine",                      "I12FW2W108","INGY 2 Point"},
                                                           {"7",  "Ponderosa pine",                      "I12FW2W122","INGY 2 Point"},
                                                           {"7",  "Douglas fir",                         "I12FW2W202","INGY 2 Point"},
                                                           {"9",  "Western hemlock",                     "F00FW2W263","Flewelling Westside"},
                                                           {"9",  "Douglas fir",                         "F03FW2W202","Flewelling Westside"},
                                                           {"9",  "Sitka spruce",                        "F03FW2W263","Flewelling Westside"},
                                                           {"10", "Douglas fir",                         "F06FW2W202","Flewelling 2 Point"},
                                                           {"10", "Ponderosa pine",                      "I00FW2W073","INGY 2 Point"},
                                                           {"10", "White fir",                           "I00FW2W093","INGY 2 Point"},
                                                           {"10", "Western hemlock",                     "F06FW2W263","fLEWELLING 2 Point"},
                                                           {"12", "Douglas fir",                         "F00FW2W202","Flewelling 2 Point"},
                                                           {"12", "Western hemlock",                     "F03FW2W263","Flewelling 2 Point"},
                                                           {"14", "Subalpine fir",                       "I00FW2W019","INGY 2 Point"},
                                                           {"14", "Engelmann's spruce",                  "I00FW2W093","INGY 2 Point"},
                                                           {"14", "Lodgepole pine",                      "I00FW2W108","INGY 2 Point"},
                                                           {"14", "Douglas/White fir/Grand fir",         "I13FW2W017","INGY 2 Point"},
                                                           {"14", "Ponderosa pine",                      "I13FW2W122","INGY 2 Point"},
                                                           {"14", "Western larch",                       "I13FW2W202","INGY 2 Point"},
                                                           {"15", "Douglas fir",                         "F00FW2W202","Flewelling 2 Point"},
                                                           {"15", "Western hemlock",                     "I11FW2W260","INGY 2 Point"},
                                                           {"15", "White fir",                           "I00FW2W017","INGY 2 Point"},
                                                           {"15", "Lodgepole pine",                      "I00FW2W108","INGY 2 Point"},
                                                           {"15", "Ponderosa pine/incense cedar",        "I00FW2W073","INGY 2 POINT"},
                                                           {"15", "Mountain hemlock",                    "I00FW2W242","INGY 2 Point"},
                                                           {"15", "Engelmann's spruce",                  "I00FW2W093","INGY 2 Point"},
                                                           {"15", "Shasta fir/Red cedar",                "I00FW2W012","INGY 2 Point"},
                                                           {"15", "Knob Cone pine",                      "I00FW2W260","Flewelling 2 Point"},
                                                           {"15", "Pacific Silver fir",                  "I13FW2W017","INGY 2 Point"},
                                                           {"16", "Grand/White fir",                     "I11FW2W017","INGY 2 Point"},
                                                           {"16", "Ponderosa pine",                      "I11FW2W122","INGY 2 Point"},
                                                           {"16", "Douglas fir",                         "I11FW2W202","INGY 2 Point"},
                                                           {"16", "Western larch",                       "I13FW2W073","INGY 2 Point"},
                                                           {"16", "Lodgepole pine",                      "I00FW2W108","INGY 2 Point"},
                                                           {"16", "Engelmann's spruce",                  "I11FW2W093","INGY 2 Point"},
                                                           {"17", "Ponderosa pine/Western larch",        "I11FW2W122","INGY 2 Point"},
                                                           {"17", "Douglas fir",                         "I12FW2W202","INGY 2 Point"},
                                                           {"17", "Douglas fir",                         "I00FW2W202","INGY 2 Point"},
                                                           {"17", "Ponderosa pine",                      "I12FW2W122","INGY 2 Point"},
                                                           {"17", "Lodgepole pine",                      "I12FW2W108","INGY 2 Point"},
                                                           {"17", "Engelmann's spruce",                  "I11FW2W093","INGY 2 Point"},
                                                           {"17", "Grand fir",                           "I11FW2W017","INGY 2 Point"},
                                                           {"18", "Douglas fir",                         "F05FW2W202","Flewelling 2 Point"},
                                                           {"18", "Noble fir",                           "I00FW2W108","Flewelling 2 Point"},
                                                           {"18", "Western hemlock",                     "F03FW2W263","Flewelling 2 Point"},
                                                           {"18", "Grand fir",                           "I00FW2W017","INGY 2 Point"},
                                                           {"21", "Douglas/Alpine fir",                  "I11FW2W202","INGY 2 Point"},
                                                           {"21", "Lodgepole pine",                      "I11FW2W108","INGY 2 Point"},
                                                           {"21", "Western larch",                       "I11FW2W073","INGY 2 Point"},
                                                           {"21", "Western red cedar",                   "I11FW2W242","INGY 2 Point"},
                                                           {"21", "Engelmann's spruce",                  "I13FW2W093","INGY 2 Point"},
                                                           {"21", "Grand fir/Hemlock",                   "I11FW2W017","INGY 2 Point"},
                                                           {"21", "Ponderosa pine",                      "I12FW2W122","INGY 2 Point"},
                                                           {"21", "White pine",                          "I00FW2W119","INGY 2 Point"}};

        //  Region 10 equations
        public string[,] volumeArray10 = new string[13,4] {{"ALL","Red alder",            "A32CURW351","Curtis Profile Model"},
                                                          {"ALL","Sitka spruce",         "A00F32W098","Flewelling Profile-32ft Log Rule"},
                                                          {"ALL","Western hemlock",      "A00F32W263","Flewelling Profile-32ft Log Rule"},
                                                          {"4",  "White spruce",         "A00DVEW094","Larson Volume Equation"},
                                                          {"4",  "Black spruce",         "A00DVEW094","Larson Volume Equation"},
                                                          {"4",  "Cottongwood",          "A00DVEW747","Larson Volume Equation"},
                                                          {"4",  "Mountain hemlock",     "A01DEMW263","Demars Profile Model"},
                                                          {"4",  "Paper birch",          "A00DVEW375","Larson Volume Equation"},
                                                          {"4",  "Quaking aspen",        "A00DVEW351","Larson Volume Equation"},
                                                          {"5",  "Alaska yellow cedar",  "A00F32W042","Flewelling Profile-32ft Log Rule"},
                                                          {"5",  "Western redcedar",     "A00F32W242","Flewelling Profile-32ft Log Rule"},
                                                          {"5",  "Hemlock-second growth","A02F32W263","Flewelling Profile-32ft Log Rule"},
                                                          {"5",  "Spruce-second growth", "A02F32W098","Flewelling Profile-32ft Log Rule"}};
        //  DOD equations ("Region 11")
        public string[,] volumeArray11 = new string[20, 4] {{"ALL","Douglas fir","F00FW2W202","Flewelling 2 Point"},
                                                           {"ALL","Douglas fir","F02FW2W202","Flewelling 2 Point"},
                                                           {"ALL","Douglas fir","F07FW2W202","Flewelling 2 Point"},
                                                           {"ALL","Douglas fir","F00F32W202","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Douglas fir","F02F32W202","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Douglas fir","F07F32W202","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western hemlock","F00FW2W263","Flewelling 2 Point"},
                                                           {"ALL","Western hemlock","F02FW2W263","Flewelling 2 Point"},
                                                           {"ALL","Western hemlock","F07FW2W263","Flewelling 2 Point"},
                                                           {"ALL","Western hemlock","F00F32W263","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western hemlock","F02F32W263","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western hemlock","F07F32W263","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western redcedar","F00FW2W242","Flewelling 2 Point"},
                                                           {"ALL","Western redcedar","F02FW2W242","Flewelling 2 Point"},
                                                           {"ALL","Western redcedar","F07FW2W242","Flewelling 2 Point"},
                                                           {"ALL","Western redcedar","F00F32W242","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western redcedar","F02F32W242","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Western redcedar","F07F32W242","Flewelling Profile-32ft Log Rule"},
                                                           {"ALL","Other species","616BEHW000","Behre's Hyperbola"},
                                                           {"ALL","Other species","628BEHW000","Behre's Hyperbola"}};
    }
}
